server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital?characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 123456
